apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: microservices-app
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
    </source>

    <match kubernetes.**>
      @type elasticsearch
      @log_level info
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme http
      logstash_format true
      include_tag_key true
      type_name access_log
      flush_interval 5s
    </match>
