apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices-app
  name: microservices-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-rolebinding
  namespace: microservices-app
subjects:
  - kind: ServiceAccount
    name: default
    namespace: microservices-app
roleRef:
  kind: Role
  name: microservices-role
  apiGroup: rbac.authorization.k8s.io
