apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: microservices-app
spec:
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
