apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: microservices-app
spec:
  selector:
    app: fluentd
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224
    - protocol: UDP
      port: 24224
      targetPort: 24224
  type: ClusterIP
